{
 "title": "todolist",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "quantile", "label": "quantile", "query": "0.5,0.95,0.99,0.999,1" },
   { "name": "job", "label": "job", "query": "todolist" }
  ]
 },
 "panels": [
  {
   "title": "HTTP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Success by method",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(http_requests_total{job=\"$job\", status=~\"2..\"}[$__rate_interval])) by (pattern)",
       "legendFormat": "{{pattern}}"
      },
      {
       "expr": "sum(rate(http_requests_total{job=\"$job\", status=~\"2..\"}[$__rate_interval]))",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "Timings by method($quantile)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg(histogram_quantile($quantile, sum by(le, pattern, host) (rate(http_request_duration_seconds_bucket{job=\"$job\"}[$__rate_interval])))) by (pattern)",
       "legendFormat": "{{pattern}}"
      }
     ]
    },
    {
     "title": "4xx by method",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(irate(http_requests_total{job=\"$job\", status=~\"4..\"}[1m])) by (pattern, status)",
       "legendFormat": "{{pattern}} - {{status}}"
      }
     ]
    },
    {
     "title": "5xx by method",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(irate(http_requests_total{job=\"$job\", status=~\"5..\"}[1m])) by (pattern, status)",
       "legendFormat": "{{pattern}} - {{status}}"
      }
     ]
    }
   ]
  },
  {
   "title": "MaxBot",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Success by method",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(maxbot_requests_total{job=\"$job\", error=~\"false\"}[$__rate_interval])) by (method)",
       "legendFormat": "{{method}}"
      },
      {
       "expr": "sum(rate(maxbot_requests_total{job=\"$job\", error=~\"false\"}[$__rate_interval]))",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "Timings by method($quantile)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg(histogram_quantile($quantile, sum by(le, method, host) (rate(maxbot_requests_duration_seconds{job=\"$job\"}[$__rate_interval])))) by (method)",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Erros by method",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(maxbot_requests_total{job=\"$job\", error=~\"true\"}[$__rate_interval])) by (method)",
       "legendFormat": "{{method}}"
      },
      {
       "expr": "sum(rate(maxbot_requests_total{job=\"$job\", error=~\"true\"}[$__rate_interval]))",
       "legendFormat": "total"
      }
     ]
    }
   ]
  },
  {
   "title": "Subscriber",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Processed by method",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(subscriber_requests_total{job=\"$job\"}[$__rate_interval])) by (method)",
       "legendFormat": "{{method}}"
      },
      {
       "expr": "sum(rate(subscriber_requests_total{job=\"$job\"}[$__rate_interval]))",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "Timings by method($quantile)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg(histogram_quantile($quantile, sum by(le, method) (rate(subscriber_requests_duration_seconds_bucket{job=\"$job\"}[$__rate_interval])))) by (method)",
       "legendFormat": "{{method}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Postgre",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Timings (${quantile})",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 186 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg(histogram_quantile($quantile, sum(irate(postgres_request_duration_seconds_bucket{job=\"$job\"}[$__rate_interval])) by (le, action))) by (action)",
       "legendFormat": "{{action}}"
      }
     ]
    },
    {
     "title": "Success",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 186 },
     "targets": [
      {
       "expr": "sum(rate(postgres_request_duration_seconds_count{job=~\"$job\",error=\"false\"}[$__rate_interval])) by (action)",
       "legendFormat": "{{action}}"
      }
     ]
    },
    {
     "title": "Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 194 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg(histogram_quantile(0.5, sum(irate(postgres_request_duration_seconds_bucket{job=~\"$job\"}[$__rate_interval])) by (le, action)))",
       "legendFormat": "0.5"
      },
      {
       "expr": "avg(histogram_quantile(0.95, sum(irate(postgres_request_duration_seconds_bucket{job=~\"$job\"}[$__rate_interval])) by (le, action)))",
       "legendFormat": "0.95"
      },
      {
       "expr": "avg(histogram_quantile(0.99, sum(irate(postgres_request_duration_seconds_bucket{job=~\"$job\"}[$__rate_interval])) by (le, action)))",
       "legendFormat": "0.99"
      },
      {
       "expr": "avg(histogram_quantile(0.999, sum(irate(postgres_request_duration_seconds_bucket{job=~\"$job\"}[$__rate_interval])) by (le, action)))",
       "legendFormat": "0.999"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 194 },
     "targets": [
      {
       "expr": "sum(rate(postgres_request_duration_seconds_count{job=~\"$job\",error=\"true\"}[$__rate_interval])) by (action)",
       "legendFormat": "{{action}}"
      }
     ]
    },
    {
     "title": "Success by host",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 202 },
     "targets": [
      {
       "expr": "sum(rate(postgres_request_duration_seconds_count{job=~\"$job\",error=\"false\"}[1m])) by (addr)",
       "legendFormat": "{{action}}"
      }
     ]
    },
    {
     "title": "Errors by host",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 202 },
     "targets": [
      {
       "expr": "sum(rate(postgres_request_duration_seconds_count{job=~\"$job\",error=\"true\"}[1m])) by (addr)",
       "legendFormat": "{{action}}"
      }
     ]
    },
    {
     "title": "Timings by host(${quantile})",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 210 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg(histogram_quantile($quantile, sum(irate(postgres_request_duration_seconds_bucket{job=~\"$job\"}[$__rate_interval])) by (le, addr))) by (addr)",
       "legendFormat": "{{action}}"
      }
     ]
    },
    {
     "title": "Connections",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 218 },
     "targets": [
      {
       "expr": "sum(postgres_pool_connections{job=\"$job\"}) by (addr, status)",
       "legendFormat": "{{ addr }} - {{ status }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Redis",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Timings (${quantile})",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg(histogram_quantile($quantile, sum(irate(redis_pool_action_duration_seconds_bucket{job=~\"$job\"}[$__rate_interval])) by (le, action, name))) by (action, name)",
       "legendFormat": "{{action}} - {{name}}"
      }
     ]
    },
    {
     "title": "Success",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
     "targets": [
      {
       "expr": "sum(rate(redis_pool_action_duration_seconds_count{job=~\"$job\",error=\"false\"}[$__rate_interval])) by (action, name)",
       "legendFormat": "{{action}} - {{name}}"
      }
     ]
    },
    {
     "title": "Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg(histogram_quantile(0.5, sum(irate(redis_pool_action_duration_seconds_bucket{job=~\"$job\"}[$__rate_interval])) by (le, action, name)))",
       "legendFormat": "0.5"
      },
      {
       "expr": "avg(histogram_quantile(0.95, sum(irate(redis_pool_action_duration_seconds_bucket{job=~\"$job\"}[$__rate_interval])) by (le, action, name)))",
       "legendFormat": "0.95"
      },
      {
       "expr": "avg(histogram_quantile(0.99, sum(irate(redis_pool_action_duration_seconds_bucket{job=~\"$job\"}[$__rate_interval])) by (le, action, name)))",
       "legendFormat": "0.99"
      },
      {
       "expr": "avg(histogram_quantile(0.999, sum(irate(redis_pool_action_duration_seconds_bucket{job=~\"$job\"}[$__rate_interval])) by (le, action, name)))",
       "legendFormat": "0.999"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
     "targets": [
      {
       "expr": "sum(rate(redis_pool_action_duration_seconds_count{job=~\"$job\",error=\"true\"}[$__rate_interval])) by (action, name)",
       "legendFormat": "{{action}} - {{name}}"
      }
     ]
    },
    {
     "title": "Timings  single command (${quantile})",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 77 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg(histogram_quantile($quantile, sum(irate(redis_single_commands_bucket{job=~\"$job\", command != \"ping\"}[$__rate_interval])) by (le, host, command, error, name))) by (command, error, name)",
       "legendFormat": "{{name}}:{{ command }}:{{error}}"
      }
     ]
    },
    {
     "title": "Success",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 85 },
     "targets": [
      {
       "expr": "sum(redis_pool_connections{job=\"$job\", status!=\"stale\"}) by (host, name, status)",
       "legendFormat": "{{host}}:{{name}} - {{status}}"
      }
     ]
    },
    {
     "title": "Create pool connections",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 7, "x": 8, "y": 85 },
     "targets": [
      {
       "expr": "sum(rate(redis_pool_connection_created_total{job=\"$job\"}[$__rate_interval])) by (name, addr)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Create pool connections",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 15, "y": 85 },
     "targets": [
      {
       "expr": "sum(rate(redis_pool_connections_calls{job=\"$job\"}[$__rate_interval])) by (name, status)",
       "legendFormat": "{{ name }}:{{status}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Go stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg(rate(process_cpu_seconds_total{job=\"$job\"}[$__interval])) by (__name__)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Resident memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg(rate(go_memstats_alloc_bytes_total{job=\"$job\"}[$__rate_interval])) by (__name__)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Heap & Stack",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 305 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg(go_memstats_heap_inuse_bytes{job=\"$job\"}) by (__name__)",
       "legendFormat": " Heap"
      },
      {
       "expr": "avg(go_memstats_stack_inuse_bytes{job=\"$job\"}) by (__name__)",
       "legendFormat": "Stack"
      }
     ]
    },
    {
     "title": "Total allocations",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 305 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(go_memstats_alloc_bytes_total{job=\"$job\"}[$__rate_interval])) by (__name__)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "GC Timings",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 313 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg(go_gc_duration_seconds{job=\"$job\"}) by (__name__)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Goroutines Total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 321 },
     "targets": [
      {
       "expr": "avg(go_goroutines{job=\"$job\"}) by (__name__)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Goroutines Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 321 },
     "targets": [
      {
       "expr": "avg(rate(go_goroutines{job=\"$job\"}[$__rate_interval])) by (__name__)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}